export const BookData = [
    {
        id: 0,
        book_name: "The Kid Who Came From Space",
        book_description:"The Kid Who Came From Space by Ross Welford is a science fiction novel that tells the story of Ethan, a boy whose twin sister, Tammy, mysteriously disappears. As Ethan searches for Tammy, he encounters a strange boy named Hellyann, who claims to be from another planet. Together, they embark on a thrilling adventure to uncover the truth about Tammy's disappearance, navigating through a world filled with secrets, advanced technology, and intergalactic mysteries. The novel blends elements of science fiction and adventure, while exploring themes of friendship, family, and the unknown.",
        book_url: "https://encrypted-tbn2.gstatic.com/shopping?q=tbn:ANd9GcSNnpd3mVBwmi2AM7-UpCzgTcsmZ9ittI2kC8fu0oUvs-FsAef4Yu-UCv9BTqI7nVFHhjOEeRA0JtlaecUWuRMJDaxOb99Y9OYKlFnRTMJ-2LPEemydOwCb&usqp=CAE",
        print_length: "345 pages",
        language: "English",
        author_name: "Ross Welford",
        price: "305",
        pdf_url:"https://www.readingzone.com/media/ceqpvkd0/thekidwhocamefromspace_chapter1.pdf"
    },
    {
        id: 1,
        book_name: "Beauty and the Beast",
        book_description: "Beauty and the Beast is a classic fairy tale about a kind and intelligent young woman named Belle who becomes a prisoner in a castle owned by a fearsome Beast. Despite the Beast's frightening appearance, Belle eventually discovers his kind heart and gentle nature. Through their growing friendship and mutual understanding, they both learn that true beauty comes from within. As their love deepens, the curse on the Beast is broken, revealing him to be a handsome prince. The story emphasizes the themes of inner beauty, kindness, and the transformative power of love.",
        book_url: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQGYtckWEmOKCIkzl14vDvmQs-hlzJNO_PwGnVQPnfc_ETo8i6u",
        print_length: "200 pages",
        language: "English",
        author_name: "Jeanne-Marie Leprince ",
        price: "340",
        pdf_url:"https://digital.library.mcgill.ca/images/chapbooks/pdfs/PN970_K49_H5_1840.pdf",
    },
    {
        id: 2,
        book_name: "Thumbelina. An Illustrated ",
        book_description: "Thumbelina is a fairy tale written by Danish author Hans Christian Andersen. It tells the story of a tiny girl, no bigger than a thumb, who embarks on a series of adventures after being abducted by a toad. The tale is known for its themes of kindness, courage, and the search for belonging. Thumbelina is one of Andersen's most beloved stories and has been illustrated by various artists over the years, bringing its magical world to life for readers of all ages.",
        book_url: "https://cdn.kobo.com/book-images/1391bd17-77e5-4959-88df-b0fcd8f06d88/353/569/90/False/thumbelina-classic-fairy-tales-for-children-fully-illustrated.jpg",
        print_length: "236 pages",
        language: "English",
        author_name: "Hans Christian Andersen",
        price: "108",
        pdf_url:"https://www.samantha.ru/Pro/Upload/wysiwyg/Thumbelina.pdf",
    },
    {
        id: 3,
        book_name: "Little Red  Riding Hood",
        book_description: "Little Red Riding Hood is a classic fairy tale about a young girl who goes to visit her grandmother, carrying a basket of food. Along the way, she encounters a cunning wolf who tricks her into revealing the location of her grandmother's house. The wolf arrives first, disguises himself as the grandmother, and waits for Little Red Riding Hood. Depending on the version, the story often ends with a woodsman or hunter saving Little Red Riding Hood and her grandmother from the wolf.",
        book_url: "https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcR_MGNRnqKWfCYP1NXmXy3RNOdPp4MRhS3GBpHxsrh98y7w8s9L",
        print_length: "240 pages",
        language: "English",
        author_name: "Charles Perrault ",
        price: "202",
        pdf_url:"https://lionwoodinfant.co.uk/wp-content/uploads/2021/01/Yr2-Little-Red-Riding-Hood-Story-PowerPoint.pdf",
    },
    {
        id: 4,
        book_name: "Ali BaBa and Forty Thieves",
        book_description: "li Baba and the Forty Thieves is a famous tale from the Middle Eastern collection One Thousand and One Nights (also known as Arabian Nights). The story follows Ali Baba, a poor woodcutter who discovers a secret cave belonging to a band of forty thieves. The cave, which opens with the magic phrase Open Sesame, is filled with treasure. Ali Baba takes some of the treasure, but the thieves discover his actions and plot to kill him. With the help of his clever and resourceful servant girl, Morgiana, Ali Baba thwarts the thieves' plans and ultimately secures the treasure for himself, living in wealth and safety.",
        book_url: "https://encrypted-tbn2.gstatic.com/images?q=tbn:ANd9GcT8DUaXTnQvKEnh5jZUgydKP4lITlVUBUSbBAd2Axs-gGPPcnXo",
        print_length: "248 pages",
        language: "English",
        author_name: "Jules Verne",
        price: "140",
        pdf_url:"https://www.arvindguptatoys.com/arvindgupta/ali-baba-tales.pdf",
    },
    {
        id: 5,
        book_name: "The Cat In The Hat",
        book_description: "The Cat in the Hat is a beloved children's book by Dr. Seuss. It tells the story of two children who are visited by a mischievous, talking cat wearing a tall striped hat. The Cat, along with his companions Thing 1 and Thing 2, brings chaos and fun into the house while their mother is away. Despite the mess they create, the Cat ultimately cleans everything up before their mother returns, leaving no trace of their antics. The book is celebrated for its playful rhymes and whimsical illustrations.",
        book_url: "https://encrypted-tbn3.gstatic.com/shopping?q=tbn:ANd9GcRkbnn1JSiKUfzvoCiIT-ONIhzE3Aqueqx-Z3oyKuXB-1sBmcCWezYXpQyGzwF9eeAUeD7qDwa31HSWteq0W3FTL94Ld-Qgq0jgIWe-dFKF9HkOpXvM7s9Blg&usqp=CAc",
        print_length: "172 pages",
        language: "English",
        author_name: "Paulo Coelho",
        price: "286",
        pdf_url:"https://dsenglishteamweb.wordpress.com/wp-content/uploads/2020/02/kupdf.net_dr-seuss-the-cat-in-the-hat-book-pdf1.pdf",
    },
    {
        id: 6,
        book_name: "To Kill a Mockingbird",
        book_description: "Shoot all the bluejays you want, if you can hit 'em, but remember it's a sin to kill a mockingbird.' A lawyer's advice to his children as he defends the real mockingbird of Harper Lee's classic novel - a black man falsely charged with the rape of a white girl. Through the young eyes of Scout and Jem Finch, Harper Lee explores with exuberant humour the irrationality of adult attitudes to race and class in the Deep South of the 1930s. The conscience of a town steeped in prejudice, violence and hypocrisy is pricked by the stamina of one man's struggle for justice. But the weight of history will only tolerate so much. To Kill a Mockingbird is a coming-of-age story, an anti-racist novel, a historical drama of the Great Depression and a sublime example of the Southern writing tradition.",
        book_url: "https://m.media-amazon.com/images/I/51Z9p5AecCL._SX307_BO1,204,203,200_.jpg",
        print_length: "320 pages",
        language: "English",
        author_name: "Harper Lee",
        price: "138",
        pdf_url:"https://www.raio.org/TKMFullText.pdf",
    },
    {
        id: 7,
        book_name: "Do Epic Shit",
        book_description: "Ankur Warikoo is an entrepreneur and content creator whose deep, witty and brutally honest thoughts on success and failure, money and investing, self-awareness and personal relationships have made him one of India’s top personal brands. In his first book, Ankur puts together the key ideas that have fuelled his journey – one that began with him wanting to be a space engineer and ended with him creating content that has been seen and read by millions. His thoughts range from the importance of creating habits for long-term success to the foundations of money management, from embracing and accepting failure to the real truth about learning empathy. This is a book to be read, and reread, a book whose lines you will underline and think about again and again, a book you will give your family and friends and strangers. Ankur hopes for this book to become the most gifted book ever!",
        book_url: "https://m.media-amazon.com/images/I/41oYp387k8L._SY264_BO1,204,203,200_QL40_FMwebp_.jpg",
        print_length: "320 pages",
        language: "English",
        author_name: "Ankur Warikoo",
        price: "312",
        pdf_url:"",
    },
    {
        id: 8,
        book_name: "Harry Potter and the Chamber of Secrets",
        book_description: "Harry Potter's summer has included the worst birthday ever, doomy warnings from a house-elf called Dobby, and rescue from the Dursleys by his friend Ron Weasley in a magical flying car! Back at Hogwarts School of Witchcraft and Wizardry for his second year, Harry hears strange whispers echo through empty corridors - and then the attacks start. Students are found as through turned to stone . Dobby's sinister predictions seem to be coming true.These new editions of the classic and internationally bestselling, multi-award-winning series feature instantly pick-up-able new jackets by Jonny Duddle, with huge child appeal, to bring Harry Potter to the next generation of readers. It's time to PASS THE MAGIC ON .",
        book_url: "https://m.media-amazon.com/images/I/51yzj3H34aL._SY264_BO1,204,203,200_QL40_FMwebp_.jpg",
        print_length: "224 pages",
        language: "English",
        author_name: "J.K. Rowling",
        price: "310",
        pdf_url:"https://www.apsmhow.edu.in/Library%20Portal/index_htm_files/Harry%20Potter%20and%20the%20%20CHAMBER%20OF%20SECRETS.pdf",
    },
    {
        id: 9,
        book_name: "Rapunzel",
        book_description: "Rapunzel is a classic fairy tale about a young girl with long, golden hair who is imprisoned in a tower by a wicked witch. The only way to enter the tower is by climbing up Rapunzel's hair, which she lets down when the witch calls for her. One day, a prince hears Rapunzel singing and discovers her in the tower. They fall in love, and Rapunzel secretly sees him. Eventually, the witch discovers their meetings and separates them. However, they are reunited in the end, and the story concludes with Rapunzel and the prince living happily ever after",
        book_url: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSL3qT2CRER4BGX3iYkLddpbUkQWwTYPmCLr6FQ92GtM3nNpW4B",
        print_length: "384 pages",
        language: "English",
        author_name: "Mark Manson",
        price: "272",
        pdf_url:"https://stbrigidspsballymoney.com/assets/documents/HOME-LEARNING-SECTION/YEAR-1/Rapunzel-story-powerpoint-_p1-1.pdf",

    },
    {
        id: 10,
        book_name: "Ikigai",
        book_description: "THE INTERNATIONAL BESTSELLER We all have an ikigai. It's the Japanese word for ‘a reason to live’ or ‘a reason to jump out of bed in the morning’. It’s the place where your needs, desires, ambitions, and satisfaction meet. A place of balance. Small wonder that finding your ikigai is closely linked to living longer. Finding your ikigai is easier than you might think. This book will help you work out what your own ikigai really is, and equip you to change your life. You have a purpose in this world: your skills, your interests, your desires and your history have made you the perfect candidate for something. All you have to do is find it. Do that, and you can make every single day of your life joyful and meaningful.",
        book_url: "https://m.media-amazon.com/images/I/51xwGSNX-EL._SX356_BO1,204,203,200_.jpg",
        print_length: "208 pages",
        language: "English",
        author_name: "Héctor García",
        price: "249",
        pdf_url:"",
    },
    {
        id: 11,
        book_name: "LINCHPIN",
        book_description: "In this compelling, accessible and purpose-filled book bestselling business author Seth Godin shows how you have the potential to make a big difference-and make yourself indispensable in the process-wherever you are.Why are some people easily outsourced, downsized, or freelanced into obscurity, while others have their pick of opportunities? In his most powerful book yet, Seth Godin argues that it's more essential than ever to become indispensable - to become a linchpin. Linchpins are the essential building blocks of great organizations: they invent, lead (regardless of title), connect others, make things happen, and create order out of chaos. They love their work and pour their best selves into it and turn each day into a kind of art - and, in today's world, they get the best jobs and the most freedom.Godin shows that the key to being indispensable is overcoming the fears that hold most of us back.",
        book_url: "https://m.media-amazon.com/images/I/51fGhgWMZKL._SX317_BO1,204,203,200_.jpg",
        print_length: "256 pages",
        language: "English",
        author_name: "Seth Godin",
        price: "294",
        pdf_url:"",
    },
    {
        id: 12,
        book_name: "Harry Potter and the Prisoner of Azkaban",
        book_description: "When the Knight Bus crashes through the darkness and screeches to a halt in front of him, it's the start of another far from ordinary year at Hogwarts for Harry Potter. Sirius Black, escaped mass-murderer and follower of Lord Voldemort, is on the run - and they say he is coming after Harry. In his first ever Divination class, Professor Trelawney sees an omen of death in Harry's tea leaves . But perhaps most terrifying of all are the Dementors patrolling the school grounds, with their soul-sucking kiss.",
        book_url: "https://m.media-amazon.com/images/I/51StPSSsneL._SX332_BO1,204,203,200_.jpg",
        print_length: "480 pages",
        language: "English",
        author_name: "J.K. Rowling",
        price: "305",
        pdf_url:"https://www.apsmhow.edu.in/Library%20Portal/index_htm_files/Harry%20Potter%20and%20the%20PRISONER%20OF%20AZKABAN.pdf",
    },
    {
        id: 13,
        book_name: "Harry Potter and the Goblet of Fire",
        book_description: "The Triwizard Tournament is to be held at Hogwarts. Only wizards who are over seventeen are allowed to enter - but that doesn't stop Harry dreaming that he will win the competition. Then at Hallowe'en, when the Goblet of Fire makes its selection, Harry is amazed to find his name is one of those that the magical cup picks out. He will face death-defying tasks, dragons and Dark wizards, but with the help of his best friends, Ron and Hermione, he might just make it through - alive!These new editions of the classic and internationally bestselling, multi-award-winning series feature instantly pick-up-able new jackets by Jonny Duddle, with huge child appeal, to bring Harry Potter to the next generation of readers. It's time to PASS THE MAGIC ON.",
        book_url: "https://m.media-amazon.com/images/I/518TIrLNpOL._SY264_BO1,204,203,200_QL40_FMwebp_.jpg",
        print_length: "640 pages",
        language: "English",
        author_name: "J.K. Rowling",
        price: "439",
        pdf_url:"https://ebookpresssite.wordpress.com/wp-content/uploads/2017/10/4_harry_potter_and_the_goblet_of_fire.pdf",
    },
    {
        id: 14,
        book_name: "Harry Potter and the Order of the Phoenix",
        book_description: "Dark times have come to Hogwarts. After the Dementors' attack on his cousin Dudley, Harry Potter knows that Voldemort will stop at nothing to find him. There are many who deny the Dark Lord's return, but Harry is not alone: a secret order gathers at Grimmauld Place to fight against the Dark forces. Harry must allow Professor Snape to teach him how to protect himself from Voldemort's savage assaults on his mind. But they are growing stronger by the day and Harry is running out of time.",
        book_url: "https://m.media-amazon.com/images/I/511+ftLvTUL._SX332_BO1,204,203,200_.jpg",
        print_length: "816 pages",
        language: "English",
        author_name: "J.K. Rowling",
        price: "475",
        pdf_url:"https://afgjilibrary.wordpress.com/wp-content/uploads/2020/05/hp5-harry-potter-and-the-order-of-the-phoenix.pdf",
    },
    {
        id: 15,
        book_name: "Harry Potter and the Half Blood Prince",
        book_description: "When Dumbledore arrives at Privet Drive one summer night to collect Harry Potter, his wand hand is blackened and shrivelled, but he does not reveal why. Secrets and suspicion are spreading through the wizarding world, and Hogwarts itself is not safe. Harry is convinced that Malfoy bears the Dark Mark: there is a Death Eater amongst them. Harry will need powerful magic and true friends as he explores Voldemort's darkest secrets, and Dumbledore prepares him to face his destiny.",
        book_url: "https://m.media-amazon.com/images/I/51XgBz54o3L._SY264_BO1,204,203,200_QL40_FMwebp_.jpg",
        print_length: "560 pages",
        language: "English",
        author_name: "J.K. Rowling",
        price: "429",
        pdf_url:"https://bayanbox.ir/view/1900879915236196677/Harry-Potter-and-the-Half-Blood-Prince-www.libpdf.blog.ir.pdf",
    },
    // {
    //     id: 16,
    //     book_name: "Harry Potter and the Deathly Hallows",
    //     book_description: "As he climbs into the sidecar of Hagrid's motorbike and takes to the skies, leaving Privet Drive for the last time, Harry Potter knows that Lord Voldemort and the Death Eaters are not far behind. The protective charm that has kept Harry safe until now is now broken, but he cannot keep hiding. The Dark Lord is breathing fear into everything Harry loves, and to stop him Harry will have to find and destroy the remaining Horcruxes. The final battle must begin - Harry must stand and face his enemy.",
    //     book_url: "https://m.media-amazon.com/images/I/51cWQIhRUTL._SY264_BO1,204,203,200_QL40_FMwebp_.jpg",
    //     print_length: "640 pages",
    //     language: "English",
    //     author_name: "J.K. Rowling",
    //     price: "431",
    // }
]